"""Create film_tegs table

Revision ID: 88d70ebaeddf
Revises: e4b765f50df2
Create Date: 2024-12-14 14:28:00.032423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d70ebaeddf'
down_revision = 'e4b765f50df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film_tegs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('add_to_db', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Time(), nullable=False),
    sa.Column('img_file', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('film_tegs_many_to_many',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['film_tegs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('film_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('film_tegs_many_to_many')
    op.drop_table('films')
    op.drop_table('film_tegs')
    # ### end Alembic commands ###
